background {
    monitor =
    path = screenshot

    blur_passes = 4
    contrast = 1
    brightness = 0.55
    vibrancy = 0.05
    vibrancy_darkness = 0.15
}

general {
    hide_cursor = true
    ignore_empty_input = true
}

input-field {
    monitor =
    size = 180, 55

    outline_thickness = 2

    dots_size = 0.4
    dots_spacing = 0.35
    dots_center = true

    outer_color = rgba(9ece6aee)

    inner_color = rgba(1a1b26dd)

    font_color = rgb(c0caf5)

    font_family = JetBrainsMono Nerd Font Mono

    fade_on_empty = true
    rounding = 12

    check_color = rgb(9ece6a)

    fail_text = Wrong password
    fail_color = rgb(f7768e)

    placeholder_text = Enter password
    placeholder_color = rgb(565f89)

    hide_input = false

    position = 0, -580
    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] echo "$(date +'%H:%M')"

    color = rgba(c0caf5ee)

    font_size = 300
    font_family = JetBrainsMono Nerd Font

    halign = center
    valign = center
}
